### ISSUE TITLE
"Move" feature for players.

### ISSUE THREAD

**Issue by Heng-Zi-Hui** [ETI-Oct2020-Team1/DevOpsRepo#12]
This feature allows users to move to their desired location viewed on the map

- [x] check for keyboard inputs
- [ ] Move player
- [ ] update map
- [ ]  +1 to day

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 5 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 6 for continuation.
