### ISSUE TITLE
"Attack" feature for players

### ISSUE THREAD

**Issue by Heng-Zi-Hui** [ETI-Oct2020-Team1/DevOpsRepo#14]
Allow the user to deal damage to the encounter enemy
- [x] Reduce encounter (rat)'s hp
- [x] Reduce player hp
- [x] Check if rat.hp <= 0
- [x] Check if player.hp <= 0
 
UI should reflect the following upon completion
- Damage to rat
- Damage to player
- Player HP

- Display combat menu

**Comment by ZechariahWong** [comment]
attack() feature implemented in my latest pull request

**Comment by weilin-c** [comment]
Close issue
