### ISSUE TITLE
"Resume game"

### ISSUE THREAD

**Issue by ZechariahWong** [ETI-Oct2020-Team1/DevOpsRepo#15]
- Allow users to resume the game from when they last saved it

- [x] Create link for #10 
- [x] Player stats
- [x] saved file
- [x] location
- [x] day

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 5 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 6 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 7 for continuation.

**Comment by weilin-c** [comment]
Completed.
