### ISSUE TITLE
"New Game" 

### ISSUE THREAD

**Issue by Heng-Zi-Hui** [ETI-Oct2020-Team1/DevOpsRepo#22]
"New Game" feature:

- [x] Should be able to allow users to start the game afresh 
- [x] Create link to feature for #10

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 5 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 6 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 7 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 8 for continuation.
