### ISSUE TITLE
Entity class

### ISSUE THREAD

**Issue by ZechariahWong** [ETI-Oct2020-Team1/DevOpsRepo#25]
Player ID should be 0
- [x] player.getID() should return a 0

- [x] ID
- [x] Name
- [x] Attack
- [x] Defense
- [x] HP

The player's id should be 0 aka initialized first
- [x] Player's statistics should be initialized as follows:
- Name: The Hero
- Damage: 2 to 4
- Defence: 1
- HP: 20

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 2.

**Comment by weilin-c** [comment]
Issue completed and closed.
