### ISSUE TITLE
Main function

### ISSUE THREAD

**Issue by ZechariahWong** [ETI-Oct2020-Team1/DevOpsRepo#29]
Set up the main function that executes and initializes objects and classes when starting the game

- [x] Init world
- [x] init player
- [ ] init ratKing
- [x] init orb of power
- [ ] init rat(s)

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 2.

**Comment by weilin-c** [comment]
Would be continuously updated and brought forward

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 4 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 5 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 6 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 7 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 8 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 9 for continuation.

**Comment by weilin-c** [comment]
Completed, Closed
