### ISSUE TITLE
"Rat King" entity

### ISSUE THREAD

**Issue by ZechariahWong** [ETI-Oct2020-Team1/DevOpsRepo#48]
- [x] Can only be killed AFTER player obtains the orb of power
- [x] if NO orb of power: rat king takes 0 damage from player
- [x] Takes the place of where 'orb of power' used to be "K"
- [x] Damage: 8-12
- [x] Defence: 5
- [x] HP: 25

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 9 for continuation.

**Comment by weilin-c** [comment]
Completed, Closed.
