### ISSUE TITLE
"Orb of power" entity

### ISSUE THREAD

**Issue by ZechariahWong** [ETI-Oct2020-Team1/DevOpsRepo#49]
- [x] Increases players stats by 5 (Excluding HP)
- [x] Reflect changes in stats view
- [x] Stats view shows that player has orb of power
- [x] Denoted with 'O'
- [x] Spawns in a random town EXCEPT starting town

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 8 for continuation.

**Comment by weilin-c** [comment]
Completed.
