### ISSUE TITLE
Map view

### ISSUE THREAD

**Issue by Heng-Zi-Hui** [ETI-Oct2020-Team1/DevOpsRepo#6]
Map should be able to display the locations of:
- [x] Towns, to allow users to locate nearby safe spots
- [x] Players, to allow user to locate where they are on the map
- [x] Katalina (K), to allow users to find the objective
- [x] Allow for player movement
- [x] Create link to feature #5 #4 #3 
- [x] "Orb of Power" placed in random to any of the towns except the starting town ("T/O")

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 4 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 5 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 6 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 7 for continuation.

**Comment by ZechariahWong** [comment]
Hi @ZechariahWong please finish this by this sprint me you've delayed this long enough

**Comment by weilin-c** [comment]
Completed.
