### ISSUE TITLE
"Save" feature for players.

### ISSUE THREAD

**Issue by Heng-Zi-Hui** [ETI-Oct2020-Team1/DevOpsRepo#8]
This feature allows users to save their data and progress. 

- [x] Save Player Statistics 
- [x] Save Day
- [x] Save Map

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 4 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 5 for continuation.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 6 for continuation.

**Comment by weilin-c** [comment]
Completed.

**Comment by weilin-c** [comment]
Will be brought forward to Sprint 7 for continuation.

**Comment by weilin-c** [comment]
Completed.
